- name: "Add privileges {{ global_privilege_item }} to user {{ role }}"
  postgresql_privs:
    login_db: "{{ privilegesdb }}"
    login_host: "{{ DBHOST }}"
    login_password: "{{ DBPASS }}"
    login_user: "{{ DBUSER }}"
    login_port: "{{ DBPORT }}"

    roles: "{{ role }}"

    type: "{{ global_privilege_item.type }}"
    objs: "{{ global_privilege_item.objects}}"
    privs: "{{ global_privilege_item.privileges }}"
    grant_option: "{{ global_privilege_item.grant_option }}"
